window.CONTACT_CONFIG = {
  page: {
    title: "Contact - Droit",
    language: "zh-CN",
  },
  hero: {
    show: true,
    showAlias: true,
    showNote: true,
    intro: "Hi, I'm",
    name: "Droit",
    suffix: ".",
    callToAction: "You can call me",
    alias: "Right",
    note: "Hello World~",
  },
  contactsShow: true,
  theme: {
    backgroundStart: "#f2f4f8",
    backgroundEnd: "#dce2ec",
    cardBackground: "rgba(255, 255, 255, 0.72)",
    textPrimary: "#1e2633",
    textMuted: "rgba(30, 38, 51, 0.72)",
    aliasBackground: "rgba(54, 78, 111, 0.12)",
    aliasText: "#24344e",
  },
  contacts: [
    {
      show: true,
      label: "GitHub",
      url: "https://github.com/right202209",
      color: "#181717",
      icon: "GH",
      iconClass: "icon-github",
    },
    {
      show: true,
      label: "Email",
      url: "mailto:tunhe38@gmail.com",
      color: "#d44638",
      icon: "EM",
      iconClass: "icon-email",
    },
    {
      show: false,
      label: "网易云音乐",
      url: "",
      color: "#c20c0c",
      icon: "MU",
    },
    {
      show: false,
      label: "RSS",
      url: "",
      color: "#ffa500",
      icon: "RS",
    },
    {
      show: true,
      label: "X",
      url: "https://x.com/tunhe245960",
      color: "#f00000",
      icon: "X",
      iconClass: "icon-X",
    },
  ],
};
