window.CONTACT_CONFIG = {
  page: {
    title: "Contact - Your Name",
    language: "en",
  },
  hero: {
    show: true,
    showAlias: true,
    showNote: true,
    noteMode: "eyes",
    intro: "Hi, I'm",
    name: "Your Name",
    suffix: ".",
    callToAction: "You can call me",
    alias: "Nickname",
    note: "Hello World~",
    eyes: {
      maxOffsetRatio: 0.22,
      eyeTiltMax: 10,
      containerTiltMax: 4,
      autoBlink: true,
    },
  },
  contactsShow: true,
  emptyStateText: "No contact methods available right now.",
  theme: {
    backgroundStart: "#313131",
    backgroundEnd: "#0a0a0a",
    titleColor: "#ffffff",
    subtitleColor: "rgba(255, 255, 255, 0.85)",
    noteColor: "rgba(255, 255, 255, 0.75)",
    aliasBackground: "rgba(255, 255, 255, 0.12)",
    eyePupilColor: "#101622",
    eyeWhiteColor: "#ffffff",
    cursorDefault: "url(https://cdn.jsdelivr.net/gh/Tomotoes/images/blog/default.cur), auto",
    cursorPointer: "url(https://cdn.jsdelivr.net/gh/Tomotoes/images/blog/pointer.cur), auto",
  },
  contacts: [
    {
      show: true,
      label: "GitHub",
      url: "https://github.com/your-username",
      newTab: true,
      color: "#181717",
      icon: "GH",
      iconName: "github",
    },
    {
      show: true,
      label: "Email",
      url: "mailto:your-email@example.com",
      newTab: true,
      color: "#d44638",
      icon: "EM",
      iconName: "email",
    },
    {
      show: false,
      label: "Music",
      url: "",
      color: "#c20c0c",
      icon: "MU",
      iconName: "music",
    },
    {
      show: false,
      label: "RSS",
      url: "https://example.com/feed.xml",
      color: "#ffa500",
      icon: "RS",
      iconName: "rss",
    },
    {
      show: false,
      label: "X",
      url: "https://x.com/your-handle",
      newTab: true,
      color: "#000000",
      icon: "X",
      iconName: "x",
    },
    {
      show: false,
      label: "Instagram",
      url: "https://www.instagram.com/your-handle/",
      newTab: true,
      color: "#e1306c",
      icon: "Ins",
      iconName: "instagram",
    },
    {
      show: false,
      label: "LinkedIn",
      url: "https://www.linkedin.com/in/your-handle/",
      newTab: true,
      color: "#0a66c2",
      icon: "Li",
      iconName: "linkedin",
    },
    {
      show: false,
      label: "Telegram",
      url: "https://t.me/your-handle",
      newTab: true,
      color: "#229ed9",
      icon: "Tg",
      iconName: "telegram",
    }
  ],
};
