window.CONTACT_CONFIG = {
  page: {
    title: "Contact - Droit",
    language: "zh-CN",
  },
  hero: {
    show: true,
    showAlias: true,
    showNote: true,
    noteMode: "eyes",
    intro: "Hi, I'm",
    name: "Droit",
    suffix: ".",
    callToAction: "You can call me",
    alias: "Right",
    note: "Hello World~",
    eyes: {
      maxOffsetRatio: 0.22,
      eyeTiltMax: 10,
      containerTiltMax: 4,
      autoBlink: true,
    },
  },
  contactsShow: true,
  emptyStateText: "No contact methods available right now.",
  theme: {
    backgroundStart: "#313131",
    backgroundEnd: "#0a0a0a",
    titleColor: "#ffffff",
    subtitleColor: "rgba(255, 255, 255, 0.85)",
    noteColor: "rgba(255, 255, 255, 0.75)",
    aliasBackground: "rgba(255, 255, 255, 0.12)",
    eyePupilColor: "#101622",
    eyeWhiteColor: "#ffffff",
    cursorDefault: "url(https://cdn.jsdelivr.net/gh/Tomotoes/images/blog/default.cur), auto",
    cursorPointer: "url(https://cdn.jsdelivr.net/gh/Tomotoes/images/blog/pointer.cur), auto",
  },
  contacts: [
    {
      show: true,
      label: "GitHub",
      url: "https://github.com/right202209",
      newTab: true,
      color: "#181717",
      icon: "GH",
      iconName: "github",
    },
    {
      show: true,
      label: "Email",
      url: "mailto:tunhe38@gmail.com",
      newTab: true,
      color: "#d44638",
      icon: "EM",
      iconName: "email",
    },
    {
      show: false,
      label: "网易云音乐",
      url: "",
      color: "#c20c0c",
      icon: "MU",
    },
    {
      show: true,
      label: "RSS",
      url: "https://right202209.github.io/blog/feed.xml",
      color: "#ffa500",
      icon: "RS",
      iconName: "rss",
    },
    {
      show: true,
      label: "X",
      url: "https://x.com/droit000",
      newTab: true,
      color: "#f00000",
      icon: "X",
      iconName: "x",
    },
    {
      show: true,
      label: "Ins",
      url: "https://www.instagram.com/droit00/",
      newTab: true,
      color: "#f00000",
      icon: "Ins",
      iconName: "instagram",
    }
  ],
};
